package com.xdf.exams.bean;

import java.util.Date;



/**
 * Loginlog generated by MyEclipse - Hibernate Tools
 */

public class Loginlog  implements java.io.Serializable {


    // Fields    

     private Long loginlogid;
     private String username;
     private int success;
     private int isteacher;
     private String ip;
     private Date logtime;


    // Constructors

    /** default constructor */
    public Loginlog() {
    }

    
    /** full constructor */
    public Loginlog(String username, int success, int isteacher, String ip, Date logtime) {
        this.username = username;
        this.success = success;
        this.isteacher = isteacher;
        this.ip = ip;
        this.logtime = logtime;
    }

   
    // Property accessors

    public Long getLoginlogid() {
        return this.loginlogid;
    }
    
    public void setLoginlogid(Long loginlogid) {
        this.loginlogid = loginlogid;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public int getSuccess() {
        return this.success;
    }
    
    public void setSuccess(int success) {
        this.success = success;
    }

    public int getIsteacher() {
        return this.isteacher;
    }
    
    public void setIsteacher(int isteacher) {
        this.isteacher = isteacher;
    }

    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    public Date getLogtime() {
        return this.logtime;
    }
    
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }
   








}