package com.xdf.exams.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Student  implements java.io.Serializable {


    // Fields    

     private Long studentid;
     private String username;
     private String name;
     private String password;
     private String address;
     private String sex;
     private String email;
     private Set results = new HashSet(0);


    // Constructors

    /** default constructor */
    public Student() {
    }

	/** minimal constructor */
    public Student(String username, String name, String password, String address, String sex, String email) {
        this.username = username;
        this.name = name;
        this.password = password;
        this.address = address;
        this.sex = sex;
        this.email = email;
    }
    
    /** full constructor */
    public Student(String username, String name, String password, String address, String sex, String email, Set results) {
        this.username = username;
        this.name = name;
        this.password = password;
        this.address = address;
        this.sex = sex;
        this.email = email;
        this.results = results;
    }

   
    // Property accessors

    public Long getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set getResults() {
        return this.results;
    }
    
    public void setResults(Set results) {
        this.results = results;
    }
   








}